import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
var VariousStat = function (_a) {
    // Remove internal initiative calculation
    // const totalInitiative = dexterityTotalBonus + initiative; 
    var initiative = _a.initiative, // Use initiative directly
    speed = _a.speed, darkvision = _a.darkvision, inspiration = _a.inspiration, isEditing = _a.isEditing, onSpeedChange = _a.onSpeedChange, onDarkvisionChange = _a.onDarkvisionChange, onInspirationChange = _a.onInspirationChange;
    return (_jsxs("div", { className: "bg-zinc-800 p-4 rounded-lg", children: [_jsx("h3", { className: "text-lg font-bold text-amber-500 mb-3", children: "Character Stats" }), _jsxs("div", { className: "grid grid-cols-4 gap-3", children: [_jsxs("div", { className: "bg-zinc-700 p-2 rounded-lg", children: [_jsx("div", { className: "text-sm text-gray-400 text-center mb-1", children: "Initiative" }), _jsx("div", { className: "text-xl font-bold text-amber-500 text-center", children: initiative >= 0 ? "+".concat(initiative) : initiative })] }), _jsxs("div", { className: "bg-zinc-700 p-2 rounded-lg", children: [_jsx("div", { className: "text-sm text-gray-400 text-center mb-1", children: "Speed" }), isEditing ? (_jsx("input", { type: "number", value: speed, onChange: function (e) { return onSpeedChange(parseInt(e.target.value) || 0); }, className: "w-full bg-zinc-600 text-center rounded px-2 py-1" })) : (_jsxs("div", { className: "text-xl font-bold text-amber-500 text-center", children: [speed, " ft"] }))] }), _jsxs("div", { className: "bg-zinc-700 p-2 rounded-lg", children: [_jsx("div", { className: "text-sm text-gray-400 text-center mb-1", children: "Darkvision" }), isEditing ? (_jsx("input", { type: "number", value: darkvision, onChange: function (e) { return onDarkvisionChange(parseInt(e.target.value) || 0); }, className: "w-full bg-zinc-600 text-center rounded px-2 py-1" })) : (_jsx("div", { className: "text-xl font-bold text-amber-500 text-center", children: darkvision > 0 ? "".concat(darkvision, " ft") : "None" }))] }), _jsxs("div", { className: "bg-zinc-700 p-2 rounded-lg", children: [_jsx("div", { className: "text-sm text-gray-400 text-center mb-1", children: "Inspiration" }), isEditing ? (_jsx("input", { type: "number", value: inspiration, onChange: function (e) { return onInspirationChange(parseInt(e.target.value) || 0); }, className: "w-full bg-zinc-600 text-center rounded px-2 py-1" })) : (_jsx("div", { className: "text-xl font-bold text-amber-500 text-center", children: inspiration }))] })] })] }));
};
export default VariousStat;
